// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDraveXXz4JTuYSV6LUcGhN5IGpwKjUjXg',
    appId: '1:534907170990:web:c4c2f943bd29e227a07d3f',
    messagingSenderId: '534907170990',
    projectId: 'inventorydb-adba0',
    authDomain: 'inventorydb-adba0.firebaseapp.com',
    storageBucket: 'inventorydb-adba0.firebasestorage.app',
    measurementId: 'G-PEBSWHYFZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD12J7JZ4jZFZZuddzhwwYaz1-SqfJWkDs',
    appId: '1:534907170990:android:6b316951f564b56ea07d3f',
    messagingSenderId: '534907170990',
    projectId: 'inventorydb-adba0',
    storageBucket: 'inventorydb-adba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEp2hR0grjYwjGXbO9n2QNIx9NfoADCAs',
    appId: '1:534907170990:ios:7fe4ba0789a213a7a07d3f',
    messagingSenderId: '534907170990',
    projectId: 'inventorydb-adba0',
    storageBucket: 'inventorydb-adba0.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEp2hR0grjYwjGXbO9n2QNIx9NfoADCAs',
    appId: '1:534907170990:ios:7fe4ba0789a213a7a07d3f',
    messagingSenderId: '534907170990',
    projectId: 'inventorydb-adba0',
    storageBucket: 'inventorydb-adba0.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDraveXXz4JTuYSV6LUcGhN5IGpwKjUjXg',
    appId: '1:534907170990:web:135c619a53436b19a07d3f',
    messagingSenderId: '534907170990',
    projectId: 'inventorydb-adba0',
    authDomain: 'inventorydb-adba0.firebaseapp.com',
    storageBucket: 'inventorydb-adba0.firebasestorage.app',
    measurementId: 'G-CDLZ5Z6YDY',
  );
}
